//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Kade : Veld
	{
        public enum Position { Top, Bot };
        private int position;

		public virtual Schip Schip
		{
			get;
			set;
		}
        public Kade(Position position)
        {
            this.position = (int)position;
            Schip = new Schip();
    
        }



	}
}

