//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Model;

	public class Kar
	{

        private Boolean gevuld;

		public virtual Veld KarVeld
		{
			get;
			set;
		}

        public Kar()
        {
            gevuld = true;
        }
        public void Move()
        {
            //this.KarVeld = KarVeld.next;
        }
	}
}

