//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class GameController
	{
		public virtual BoardView BoardView
		{
			get;
			set;
		}

		public virtual InputView InputView
		{
			get;
			set;
		}

		public virtual Spel Spel
		{
			get;
			set;
		}

	}
}

