//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Kar
	{
        private Boolean Lading;


        public Kar Kar()
        {
            Lading = true;
        }
		public virtual Veld KarVeld
		{
			get;
			set;
		}

        public void LeegKar()
        {
            Lading = false;
        }

	}
}

