//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class KarBaan
	{
		public virtual int baannummer
		{
			get;
			set;
		}

		public virtual List<KarVeld> velden
		{
			get;
			set;
		}

		public virtual Loods start
		{
			get;
			set;
		}

		public virtual KarEindveld eindveld
		{
			get;
			set;
		}

		public virtual Kar Kar
		{
			get;
			set;
		}

	}
}

