//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Schip
	{
        private int Lading;

		public virtual Kade Kade
		{
			get;
			set;
		}

        public Schip(Kade kade)
        {
            this.Kade = kade;
            Lading = 0;
        }

        public Boolean KijkOfVol()
        {
            if (Lading == 8)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public void LeegSchip()
        {
            Lading = 0;
        }

	}
}

