//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Spel
	{
		public virtual Baan Baan
		{
			get;
			set;
		}

		public virtual IEnumerable<KarBaan> KarBaan
		{
			get;
			set;
		}

	}
}

