//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Veld
	{
		public virtual Kar Kar
		{
			get;
			set;
		}
        
        public virtual Veld Veld
        {
            get;
            set;
        }



	}
}

